name: RDBMS Autograding

on:
  push:
  pull_request:

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Start MySQL
        run: |
          sudo systemctl start mysql
          sudo mysql -e "SELECT VERSION();"

      - name: Run Student SQL
        run: |
          sudo mysql < starter.sql

      - name: Run Test SQL
        run: |
          sudo mysql < test.sql
